<?php $groups=['income'=>['Danh mục thu',$incomeCategories], 'expense'=>['Danh mục chi',$expenseCategories]]; ?>
<div class="card" style="margin-bottom:20px"><div class="card-body" style="padding:14px 20px">Quản lý riêng các nhóm <a href="#income">Thu</a> và <a href="#expense">Chi</a>. Xóa chỉ cập nhật trạng thái <code>99</code>.</div></div>
<?php foreach($groups as $type=>$group): ?>
<div id="<?php echo $type; ?>" class="card" style="margin-bottom:24px"><div class="card-header"><div class="card-title"><?php echo $group[0]; ?></div></div>
<div style="padding:16px 20px;background:var(--bg-surface-secondary)"><form class="category-form" action="<?php echo BASE_URL; ?>api/saveIncomeCategory" method="post" style="display:flex;gap:10px;flex-wrap:wrap;align-items:end"><input type="hidden" name="type" value="<?php echo $type; ?>"><input type="hidden" name="category_id"><div class="form-group" style="margin:0;min-width:240px;flex:1"><label class="form-label">Tên danh mục *</label><input class="form-control" name="name" required></div><div class="form-group" style="margin:0;min-width:250px;flex:2"><label class="form-label">Ghi chú</label><input class="form-control" name="note"></div><button class="btn btn-primary">Thêm danh mục</button></form></div>
<div class="card-body p-0"><div class="table-responsive"><table class="table"><thead><tr><th>STT</th><th>Tên danh mục</th><th>Ghi chú</th><th style="text-align:right">Thao tác</th></tr></thead><tbody><?php foreach($group[1] as $i=>$item): ?><tr><td><?php echo $i+1; ?></td><td><b><?php echo htmlspecialchars($item['category_name']); ?></b></td><td><?php echo htmlspecialchars($item['category_note']?:'-'); ?></td><td style="text-align:right"><button class="btn btn-outline btn-sm" type="button" onclick="editCategory(this)" data-id="<?php echo $item['category_id']; ?>" data-name="<?php echo htmlspecialchars($item['category_name'],ENT_QUOTES); ?>" data-note="<?php echo htmlspecialchars($item['category_note'],ENT_QUOTES); ?>">Sửa</button> <button class="btn btn-outline btn-sm text-danger" type="button" onclick="deleteCategory(<?php echo $item['category_id']; ?>)">Xóa</button></td></tr><?php endforeach; ?><?php if(!$group[1]): ?><tr><td colspan="4" style="text-align:center;padding:24px">Chưa có danh mục.</td></tr><?php endif; ?></tbody></table></div></div></div>
<?php endforeach; ?>
<script>
function apiForm(form){fetch(form.action,{method:'POST',body:new FormData(form)}).then(r=>r.json()).then(d=>d.status===200?location.reload():alert(d.message||'Có lỗi'));}
document.querySelectorAll('.category-form').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();apiForm(f)}));
function editCategory(b){const f=b.closest('.card').querySelector('form');f.category_id.value=b.dataset.id;f.name.value=b.dataset.name;f.note.value=b.dataset.note;f.querySelector('button').textContent='Lưu thay đổi';f.scrollIntoView({behavior:'smooth'});}
function deleteCategory(id){if(!confirm('Xóa danh mục này?'))return;let f=new FormData();f.append('category_id',id);fetch('<?php echo BASE_URL; ?>api/deleteIncomeCategory',{method:'POST',body:f}).then(r=>r.json()).then(d=>d.status===200?location.reload():alert(d.message));}
</script>
